### ISSUE TITLE
Interest in Delphes authors to be added as conda-forge feedstock maintainers?

### ISSUE THREAD

**Issue by matthewfeickert** [delphes/delphes#130]
:wave: @kratsg and I are in the process of adding Delphes to conda-forge (https://github.com/conda-forge/staged-recipes/pull/27903) as part of a larger project to try to do multiplatform packaging of the broader HEP simulation stack. Whenever I add something to conda-forge I like to also make sure that the project maintainers are aware of it and I also like to include them as feedstock maintainers so that they still have the ability to control the distribution of their project source code if they want to. This comes without any expectation of having to actually do the maintenance of the feedstock as it is unfair to expect additional work of project maintainers beyond the source code itself.

* Would the Delphes maintainers be interested in being listed as conda-forge feedstock maintainers?

* Regardless, after the feedstock recipe is merged and https://github.com/conda-forge/delphes-feedstock is generated (this doesn't exist at time of posting) would the maintainers be open to a PR that would add conda-forge install instructions using `conda` and/or `pixi` to the README?

**Comment by matthewfeickert** [comment]
There is now a working feedstock at https://github.com/conda-forge/delphes-feedstock.

@pavel-demin would you and other maintainers like to be added as maintainers on the feedstock?

**Comment by pavel-demin** [comment]
Thank you for your work on bringing Delphes to conda-forge. I have just tried running Delphes from a `pixi shell` and it worked without any problems.

My answer is yes to both of your questions. Maybe you could start by adding me as a maintainer.

I am planning to move the Delphes documentation to GitHub pages, so it might make sense to postpone your pull request until then.

**Comment by matthewfeickert** [comment]
> have just tried running Delphes from a `pixi shell` and it worked without any problems.

Great! To get it on more platforms and working with the globally pinned ROOT (c.f. https://github.com/conda-forge/delphes-feedstock/issues/2) there's some build issues that I need to fix at the moment (c.f. https://github.com/conda-forge/delphes-feedstock/pull/3). But this initial build works on x86 Linux and macOS at least. :+1: 

> Maybe you could start by adding me as a maintainer.

Done in https://github.com/conda-forge/delphes-feedstock/pull/5. Note https://github.com/conda-forge/delphes-feedstock/commit/e2f879fa08c92a278bf2230c5e02a83de63dff65#commitcomment-148722301 with instructions on how to join the conda-forge GitHub org.

> I am planning to move the Delphes documentation to GitHub pages

Nice. That sounds great.

> so it might make sense to postpone your pull request until then.

So I don't forget about it, I'll open up a PR now to just target the README. Once the website is migrated though we can add a proper section on it.

**Comment by matthewfeickert** [comment]
Resolved, so closing.
